### ISSUE TITLE
Update MORPC logo for MORPC org

### ISSUE THREAD

**Issue by rajones-hntb** [smartcitiesdata/andi#46]
Update MORPC org w/ new logo. See attached file.

![HORIZONTAL LOGOS_PRIMARY COLOR_V2.jpg](https://images.zenhubusercontent.com/5d0b82c2df158845874ae8b4/be4136e5-d17e-419d-b0bf-515c87b12cfe)

**Comment by jdenen** [comment]
@rajones-hntb Can you move this issue to a SmartColumbusOS repo?
