### ISSUE TITLE
Delete Dataset API

### ISSUE THREAD

**Issue by abrock-accenture** [smartcitiesdata/andi#57]
As a system administrator
I want the ability to easily remove a dataset and all associated data from the system
So that I can know with confidence that it has been cleaned up

ACs:

- Some programmatic interface that can remove a dataset in a single call
- The associated table should be dropped
- All stored references to the dataset should be removed (REDIS)
- All kafka topics associated with the dataset should be deleted?
- Any in-progress data ingestion for the specified dataset is terminated

*We may consider breaking these ACs up, although I would like avoid a horizontal slicing approach (such as a card per app to 'handle' deletion)*

Tech Notes: 

- Assuming this will utilize Brook and the event stream

**Comment by jeffgrunewald** [comment]
Migrated issue to umbrella project in smartcitiesdata/smartcitiesdata repo
